[package]
name = "openvm-test-secp256r1"
version = "0.1.0"
edition = "2021"

[dependencies]
revm-precompile = { git = "https://github.com/scroll-tech/revm", branch = "scroll-evm-executor/feat/v55/euclid-v2", default-features = false, features = ["secp256r1", "openvm"] }
openvm = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", features = ["std"] }
openvm-algebra-complex-macros = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", default-features = false }
openvm-algebra-guest = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", default-features = false }
openvm-bigint-guest = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", default-features = false }
#openvm-build ={ git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", default-features = false }
#openvm-circuit ={ git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", default-features = false }
#openvm-native-circuit = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", default-features = false }
#openvm-native-transpiler = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", default-features = false }
#openvm-native-compiler = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", default-features = false }
#openvm-native-recursion = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", default-features = false }
openvm-ecc-guest = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", default-features = false, features = ["k256", "p256"]}
#openvm-instructions ={ git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", default-features = false }
openvm-sha256-guest = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", default-features = false }
openvm-keccak256-guest = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", default-features = false }
openvm-pairing-guest = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", default-features = false, features = ["bn254"]}
openvm-rv32im-guest = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", branch = "main", default-features = false }

p256 = { version = "0.13.2", default-features = false, features = [
    "ecdsa",
] }
k256 = { version = "0.13.3", default-features = false, features = ["ecdsa"] }
ecdsa-core = { version = "0.16.9", package = "ecdsa", default-features = false, features = ["der"] }
primeorder = {version = "0.13"}
hex = "0.4.3"
